In [1]:
import numpy as np
import pandas as pd
import random

In [7]:
def SingularValDecompos(n):
    A = np.zeros(shape=(n,n))
    for i in range(n):
        for j in range(n):
            A[i][j] = random.randint(1,10)
    T1 = A.dot(A.transpose())
    T2 = A.transpose().dot(A)
    u_v, U = np.linalg.eig(T1)
    v_v, V = np.linalg.eig(T2)
    D = np.diag(np.sqrt(u_v))
    for i in range(n):
        for j in range(n):
            U[j][i] = U[j][i]/np.linalg.norm(U[:,i])
            V[j][i] = V[j][i]/np.linalg.norm(V[:,i])
    S = V.dot(D)
    return S.dot(U.transpose())

In [8]:
SingularValDecompos(3)

array([[ 4.27716447,  7.1839214 ,  5.9242837 ],
       [ 0.10741601,  9.51687766, -0.64614344],
       [ 2.77386479,  4.77706111,  8.91545631]])

In [2]:
a = np.zeros(shape=(3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
for i in range(3):
    for j in range(3):
        a[i][j] = random.randint(1,10)
a

array([[ 1.,  8.,  4.],
       [ 3., 10.,  1.],
       [ 5.,  2.,  1.]])

In [31]:
a[:,0]

array([8., 9., 2.])

array([4.5, 4. , 5. ])

In [4]:
for i in range(3):
    for j in range(3):
        a[i][j] = 2
a[1][1] = 6
a

array([[2., 2., 2.],
       [2., 6., 2.],
       [2., 2., 2.]])

In [5]:
x,y = np.linalg.eig(a)
x#eigenvalues

array([8.00000000e+00, 1.28830323e-16, 2.00000000e+00])

In [6]:
np.diag(np.sqrt(x))

array([[2.82842712e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.13503446e-08, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.41421356e+00]])

In [42]:
y#eigenvectors

array([[-4.08248290e-01, -7.07106781e-01,  5.77350269e-01],
       [-8.16496581e-01,  1.11954943e-16, -5.77350269e-01],
       [-4.08248290e-01,  7.07106781e-01,  5.77350269e-01]])

In [43]:
y# every column divide by length

array([[-2.04124145e-01, -3.53553391e-01,  2.88675135e-01],
       [-4.08248290e-01,  5.59774714e-17, -2.88675135e-01],
       [-2.04124145e-01,  3.53553391e-01,  2.88675135e-01]])