In [2]:
import numpy as np
import pandas as pd
import random

In [34]:
def SingularValDecompos(n):
    A = np.zeros(shape=(n,n))
    for i in range(n):
        for j in range(n):
            A[i][j] = random.randint(1,10)
    T1 = A.dot(A.transpose())
    T2 = A.transpose().dot(A)
    u_v, U = np.linalg.eig(T1)
    v_v, V = np.linalg.eig(T2)
    D = np.diag(u_v)
    for i in range(n):
        for j in range(n):
            U[j][i] = U[j][i]/np.linalg.norm(U[:,i])
            V[j][i] = V[j][i]/np.linalg.norm(V[:,i])
    S = V.dot(D)
    return S.dot(U.transpose())

In [35]:
SingularValDecompos(3)

array([[-121.43754317, -122.45095813, -104.39648881],
       [ -93.79258857,  -87.64131857,  -85.45351367],
       [-157.35905897, -162.16893085, -138.0183688 ]])

In [11]:
random.randint(1,10)

4

In [22]:
a = np.zeros(shape=(3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
for i in range(3):
    for j in range(3):
        a[i][j] = random.randint(1,10)
a

array([[ 8., 10.,  3.],
       [ 9.,  6.,  5.],
       [ 2.,  7.,  7.]])

In [31]:
a[:,0]

array([8., 9., 2.])

array([4.5, 4. , 5. ])

In [36]:
for i in range(3):
    for j in range(3):
        a[i][j] = 2
a[1][1] = 6
a

array([[2., 2., 2.],
       [2., 6., 2.],
       [2., 2., 2.]])

In [37]:
x,y = np.linalg.eig(a)
x#eigenvalues

array([8.00000000e+00, 1.28830323e-16, 2.00000000e+00])

In [38]:
np.diag(x)

array([[8.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.28830323e-16, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00]])

In [42]:
y#eigenvectors

array([[-4.08248290e-01, -7.07106781e-01,  5.77350269e-01],
       [-8.16496581e-01,  1.11954943e-16, -5.77350269e-01],
       [-4.08248290e-01,  7.07106781e-01,  5.77350269e-01]])

In [43]:
y# every column divide by length

array([[-2.04124145e-01, -3.53553391e-01,  2.88675135e-01],
       [-4.08248290e-01,  5.59774714e-17, -2.88675135e-01],
       [-2.04124145e-01,  3.53553391e-01,  2.88675135e-01]])